main: com.kzics.mplace.Main
version: 1.0
api-version: 1.20
name: mPlace
commands:
  canvas:
    description: Canvas command
  pallet:
    description: Pallet command
  blockwhitelist:
    description: Block whitelist command